# Generated by Django 4.2 on 2024-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0005_book_picture_alter_bookrating_book_delete_userstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
