# Generated by Django 4.2.10 on 2024-05-08 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0003_alter_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='comment',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
