# Generated by Django 4.2 on 2024-05-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0004_book_shares_bookrating_comment_alter_book_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookhub.book'),
        ),
        migrations.DeleteModel(
            name='UserState',
        ),
    ]
